version: '3.9'
services:
  severnode:
    container_name: projectnodedev
    ports:
      - "3000:3000"
    build: 
      context: .
      dockerfile: Dockerfile.dev
    links:
      - mongoinstance
    volumes:
      - .:/app
  mongoinstance:
    image: mongo
    container_name: projectmongodev
    ports: 
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=angel
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  
volumes:
  mongo-data:
  
