version: '3.9'
services:
  severnode:
    container_name: projectnode
    ports:
      - "3000:3000"
    build: .
    command: npm start
    links:
      - mongoinstance
  mongoinstance:
    image: mongo
    container_name: projectmongo
    ports: 
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=angel
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  
volumes:
  mongo-data:
