
# Use an official Node.js runtime as a parent image
FROM node:18

# Create app directory

RUN mkdir -p /app
RUN npm i -g nodemon
WORKDIR /app

# Expose port 3000
EXPOSE 3000

# Start the server
CMD ["nodemon","server.js"]
